// AUTO-GENERATED by Orange Sherbet — shared template runtime.
export const __esc = (v) =>
  v == null
    ? ""
    : String(v).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
export const __s = (v) => (v == null ? "" : String(v));
export const __truthy = (v) => v != null && v !== false;
